### ISSUE TITLE
Any plans to get into F-Droid?

### ISSUE THREAD

**Issue by hartwork** [aguaviva/Spectrogrammer#1]
Hi!

This would be nice to have packaged in [F-Droid](https://f-droid.org/en/), it has two related apps but not like this. Thanks for considering!

Best, Sebastian

**Comment by aguaviva** [comment]
Good point, not sure the state of the app, was it working for you?

**Comment by hartwork** [comment]
Hi @aguaviva I have no easy way of running the app without installing it through F-Droid or Google Play. I expect it would take hours to set up and figure out to compile and run it locally from scratch. My development home is Linux desktop with C and Python, for Android I'm more of a passive but amazed user these days.

**Comment by hartwork** [comment]
@aguaviva any news?

**Comment by aguaviva** [comment]
not really, I would need more people to do some testing.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
